export const icons = {
    atium: new URL('./icons/atium.png?width=100', import.meta.url),
    back: new URL('./icons/back-button.png?width=100', import.meta.url),
    clipboard: new URL('./icons/clipboard.svg', import.meta.url),
    close: new URL('./icons/close-icon.png?width=100', import.meta.url),
    github: new URL('./icons/github-icon.svg', import.meta.url),
    hamburgerMenu: new URL('./icons/hamburger-icon.png', import.meta.url),
    iceAndFire: new URL('./icons/house-stark-sigil.png?width=100', import.meta.url),
    stormlightArchive: new URL('./icons/stormlight-archive.svg', import.meta.url),
    wheelOfTime: new URL('./icons/wheel-of-time.webp?width=100', import.meta.url),
    moon: new URL('./icons/moon.svg', import.meta.url),
    sun: new URL('./icons/sun.svg', import.meta.url),
};


export const bookCovers = {
    aCrownOfSwords: new URL('./book-covers/a-crown-of-swords.jpeg', import.meta.url),
    aGameOfThrones: new URL('./book-covers/a-game-of-thrones.jpeg', import.meta.url),
    aLittleHatred: new URL('./book-covers/a-little-hatred.jpg', import.meta.url),
    aMemoryOfLight: new URL('./book-covers/a-memory-of-light.jpeg', import.meta.url),
    annaKarenina: new URL('./book-covers/anna-karenina.jpg', import.meta.url),
    ashesOfMan: new URL('./book-covers/ashes-of-man.jpg', import.meta.url),
    beforeTheyAreHanged: new URL('./book-covers/before-they-are-hanged.jpg', import.meta.url),
    bestServedCold: new URL('./book-covers/best-served-cold.jpg', import.meta.url),
    crossroadsOfTwilight: new URL('./book-covers/crossroads-of-twilight.png', import.meta.url),
    demonInWhite: new URL('./book-covers/demon-in-white.jpg', import.meta.url),
    disquietGods: new URL('./book-covers/disquiet-gods.jpg', import.meta.url),
    dune: new URL('./book-covers/dune.jpeg', import.meta.url),
    duneMessiah: new URL('./book-covers/dune-messiah.jpeg', import.meta.url),
    elantris: new URL('./book-covers/elantris.jpg', import.meta.url),
    empireOfSilence: new URL('./book-covers/empire-of-silence.jpg', import.meta.url),
    eyeOfTheWorld: new URL('./book-covers/eye-of-the-world.jpeg', import.meta.url),
    heroOfAges: new URL('./book-covers/hero-of-ages.webp', import.meta.url),
    howlingDark: new URL('./book-covers/howling-dark.jpg', import.meta.url),
    hyperion: new URL('./book-covers/hyperion.jpg', import.meta.url),
    kingdomsOfDeath: new URL('./book-covers/kingdoms-of-death.webp', import.meta.url),
    knifeOfDreams: new URL('./book-covers/knife-of-dreams.jpg', import.meta.url),
    lastArgumentOfKings: new URL('./book-covers/last-argument-of-kings.webp', import.meta.url),
    lordOfChaos: new URL('./book-covers/lord-of-chaos.png', import.meta.url),
    mistborn: new URL('./book-covers/mistborn.jpg', import.meta.url),
    newSpring: new URL('./book-covers/new-spring.jpeg', import.meta.url),
    redCountry: new URL('./book-covers/red-country.webp', import.meta.url),
    sharpEnds: new URL('./book-covers/sharp-ends.jpg', import.meta.url),
    theAnxiousGeneration: new URL('./book-covers/the-anxious-generation.jpg', import.meta.url),
    theBladeItself: new URL('./book-covers/the-blade-itself.jpg', import.meta.url),
    theClosingOfTheAmericanMind: new URL('./book-covers/the-closing-of-the-american-mind.png', import.meta.url),
    theCoddlingOfTheAmericanMind: new URL('./book-covers/the-coddling-of-the-american-mind.jpg', import.meta.url),
    theDragonReborn: new URL('./book-covers/the-dragon-reborn.jpeg', import.meta.url),
    theDregsOfEmpire: new URL('./book-covers/the-dregs-of-empire.png', import.meta.url),
    theFallOfHyperion: new URL('./book-covers/the-fall-of-hyperion.jpg', import.meta.url),
    theFiresOfHeaven: new URL('./book-covers/the-fires-of-heaven.jpg', import.meta.url),
    theGatheringStorm: new URL('./book-covers/the-gathering-storm.jpeg', import.meta.url),
    theGreatHunt: new URL('./book-covers/the-great-hunt.jpeg', import.meta.url),
    theHeroes: new URL('./book-covers/the-heroes.jpg', import.meta.url),
    theMythicalManMonth: new URL('./book-covers/the-mythical-man-month.png', import.meta.url),
    thePathOfDaggers: new URL('./book-covers/the-path-of-daggers.jpeg', import.meta.url),
    theShadowRising: new URL('./book-covers/the-shadow-rising.jpg', import.meta.url),
    theWayOfKings: new URL('./book-covers/the-way-of-kings.jpg', import.meta.url),
    theWellOfAscension: new URL('./book-covers/the-well-of-ascension.jpeg', import.meta.url),
    towersOfMidnight: new URL('./book-covers/towers-of-midnight.jpeg', import.meta.url),
    warbreaker: new URL('./book-covers/warbreaker.jpeg', import.meta.url),
    wintersHeart: new URL('./book-covers/winters-heart.jpeg', import.meta.url),
    wordsOfRadiance: new URL('./book-covers/words-of-radiance.jpg', import.meta.url),
};


export const patterns = {
    shinyGold: new URL('patterns/shiny-gold.jpg', import.meta.url),
    mist: new URL('patterns/mist2.png?width=300', import.meta.url),
    sand: new URL('patterns/sand.jpg', import.meta.url),
    highstorm: new URL('patterns/shallan.jpg', import.meta.url),
    ironThrone: new URL('patterns/iron-throne.jpg', import.meta.url),
    dragon: new URL('patterns/dragon-scales.jpg', import.meta.url),
    nebula: new URL('patterns/nebula.jpg', import.meta.url),
    needles: new URL('patterns/needles.jpg', import.meta.url),
    sun: new URL('patterns/aia-0304.jpg', import.meta.url),
    blood: new URL('patterns/bloody-handprint.jpg', import.meta.url),
    // blood: new URL('patterns/blood.jpg', import.meta.url),
}
